//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Bjørn Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerTest"",
            ""id"": ""1017d912-3de3-4bc9-a46c-2c467eeb16d4"",
            ""actions"": [
                {
                    ""name"": ""Gascrank"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7573519a-06c1-401d-b99d-8c34ba8e43aa"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3db1d5c4-dcf1-44af-96ff-8ce68503601b"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gascrank"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerTest
        m_PlayerTest = asset.FindActionMap("PlayerTest", throwIfNotFound: true);
        m_PlayerTest_Gascrank = m_PlayerTest.FindAction("Gascrank", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerTest
    private readonly InputActionMap m_PlayerTest;
    private IPlayerTestActions m_PlayerTestActionsCallbackInterface;
    private readonly InputAction m_PlayerTest_Gascrank;
    public struct PlayerTestActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerTestActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Gascrank => m_Wrapper.m_PlayerTest_Gascrank;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTestActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerTestActions instance)
        {
            if (m_Wrapper.m_PlayerTestActionsCallbackInterface != null)
            {
                @Gascrank.started -= m_Wrapper.m_PlayerTestActionsCallbackInterface.OnGascrank;
                @Gascrank.performed -= m_Wrapper.m_PlayerTestActionsCallbackInterface.OnGascrank;
                @Gascrank.canceled -= m_Wrapper.m_PlayerTestActionsCallbackInterface.OnGascrank;
            }
            m_Wrapper.m_PlayerTestActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Gascrank.started += instance.OnGascrank;
                @Gascrank.performed += instance.OnGascrank;
                @Gascrank.canceled += instance.OnGascrank;
            }
        }
    }
    public PlayerTestActions @PlayerTest => new PlayerTestActions(this);
    public interface IPlayerTestActions
    {
        void OnGascrank(InputAction.CallbackContext context);
    }
}
