//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_LawnmowerHero : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.lawnmowerHero_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.lawnmowerHero_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean YButton
        {
            get
            {
                return SteamVR_Actions.lawnmowerHero_YButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean XButton
        {
            get
            {
                return SteamVR_Actions.lawnmowerHero_XButton;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.lawnmowerHero_Haptic;
            }
        }
    }
}
